import polars as pl

SBF_BLOCK_COLUMNS_BIN2ASC = {
    "MeasEpoch2": {
        pl.UInt32: [
            "TOW [0.001 s]",
        ],
        pl.UInt16: [
            "WNc [w]",
            "MeasType",
            "Antenna ID",
            "SignalType",
            "LockTime [s]",
        ],
        pl.String: [
            "SVID",
        ],
        pl.Float64: [
            "CN0_dBHz [dB-Hz]",
            "PR_m [m]",
            "Doppler_Hz",
            "L_cycles [cyc]",
        ],
    },
    "Meas3Ranges": {
        pl.UInt16: [
            "WNc [w]",
            "LockTime [s]",
        ],
        pl.String: [
            "SVID",
            "SignalType",
            "Antenna ID",
        ],
        pl.Float64: [
            "PR [m]",
            "L [cyc]",
            "Doppler [Hz]",
            "C/N0 [dB-Hz]",
        ],
        pl.Float32: [
            "TOW [s]",
        ],
    },
    "PVTCartesian2": {
        pl.Float64: [
            "X [m]",
            "Y [m]",
            "Z [m]",
            "Vx [m/s]",
            "Vy [m/s]",
            "Vz [m/s]",
            "COG [°]",
        ],
        pl.UInt32: [
            "TOW [0.001 s]",
        ],
        pl.UInt16: [
            "WNc [w]",
            "MeanCorrAge [0.01 s]",
        ],
        pl.UInt8: [
            "Type",
            "Error",
            "NrSV",
        ],
    },
    "PVTGeodetic2": {
        pl.Float64: [
            "Latitude [rad]",
            "Longitude [rad]",
            "Height [m]",
        ],
        pl.Float32: [
            "Undulation [m]",
            "COG [°]",
        ],
        pl.UInt32: [
            "TOW [0.001 s]",
            "SignalInfo",
        ],
        pl.UInt16: [
            "WNc [w]",
            "MeanCorrAge [0.01 s]",
        ],
        pl.UInt8: [
            "Type",
            "Error",
            "NrSV",
        ],
    },
    "PosCovCartesian1": {
        pl.Float32: [
            "Cov_xx [m²]",
            "Cov_yy [m²]",
            "Cov_zz [m²]",
            "Cov_bb [s²]",
        ],
        pl.UInt32: [
            "TOW [0.001 s]",
        ],
        pl.UInt16: [
            "WNc [w]",
        ],
    },
    "PosCovGeodetic1": {
        pl.Float32: [
            "Cov_latlat [m²]",
            "Cov_lonlon [m²]",
            "Cov_hgthgt [m²]",
        ],
        pl.UInt32: [
            "TOW [0.001 s]",
        ],
        pl.UInt16: [
            "WNc [w]",
        ],
    },
    "Comment1": {
        pl.UInt32: [
            "TOW [0.001 s]",
        ],
        pl.UInt16: [
            "WNc [w]",
            "CommentLn",
        ],
        pl.Utf8: ["Comment"],
    },
    "BaseStation1": {
        pl.UInt32: [
            "TOW [0.001 s]",
        ],
        pl.UInt16: ["WNc [w]", "BaseStationID"],
        pl.UInt8: [
            "BaseType",
            "Source",
            "Datum",
        ],
        pl.Float64: [
            "X [m]",
            "Y [m]",
            "Z [m]",
        ],
    },
    "GPSNav": {
        pl.UInt32: [
            "TOW [0.001 s]",
            "t_oc [s]",
            "t_oe [s]",
        ],
        pl.UInt16: [
            "WNc [w]",
            "WN [w]",
            "IODC",
            "WNt_oc [w]",
            "WNt_oe [w]",
        ],
        pl.UInt8: [
            "PRN",
            "CAorPonL2",
            "URA",
            "health",
            "L2DataFlag",
            "IODE2",
            "IODE3",
            "FitIntFlg",
        ],
        pl.Float32: [
            "T_gd [s]",
            "a_f2 [s/s²]",
            "a_f1 [s/s]",
            "a_f0 [s]",
            "C_rs [m]",
            "DEL_N [semi-circle/s]",
            "C_uc [rad]",
            "C_us [rad]",
            "C_ic [rad]",
            "C_is [rad]",
            "C_rc [m]",
            "OMEGADOT [semi-circle/s]",
            "IDOT [semi-circle/s]",
        ],
        pl.Float64: [
            "M_0 [semi-circle]",
            "e",
            "SQRT_A [m**1/2]",
            "OMEGA_0 [semi-circle]",
            "i_0 [semi-circle]",
            "omega [semi-circle]",
        ],
        pl.Datetime: [
            "DT",
        ],
    },
    "GALNav": {
        pl.UInt32: [
            "TOW [0.001 s]",
            "t_oe [s]",
            "t_oc [s]",
        ],
        pl.UInt16: [
            "WNc [w]",
            "WNt_oe [w]",
            "WNt_oc [w]",
            "IODnav",
        ],
        pl.UInt8: [
            "PRN",
            "Source",
            "Bits 1 to 3 valid",
            "L1-BDVS",
            "L1-BHS",
            "Bits 5 to 7 valid",
            "E5bDVS",
            "E5bHS",
            "Bits 9 to 11 valid",
            "E5aDVS",
            "E5aHS",
            "Bits 13 to 15 valid",
            "Health_PRS",
            "Bits 1 to 3 valid (PRS)",
            "L1-ADVS",
            "L1-AHS",
            "Bits 5 to 7 valid (PRS)",
            "E6-ADVS",
            "E6-AHS",
            "SISA_L1E5a",
            "SISA_L1E5b",
            "SISA_L1AE6A",
            "CNAVenc",
            "E6Benc",
            "E6Cenc",
        ],
        pl.Float64: [
            "SQRT_A [m**1/2]",
            "M_0 [semi-circle]",
            "e",
            "i_0 [semi-circle]",
            "omega [semi-circle]",
            "OMEGA_0 [semi-circle]",
            "a_f0 [s]",
        ],
        pl.Float32: [
            "OMEGADOT [semi-circle/s]",
            "IDOT [semi-circle/s]",
            "DEL_N [semi-circle/s]",
            "C_uc [rad]",
            "C_us [rad]",
            "C_rc [m]",
            "C_rs [m]",
            "C_ic [rad]",
            "C_is [rad]",
            "a_f2 [s/s²]",
            "a_f1 [s/s]",
            "BGD_L1E5a [s]",
            "BGD_L1E5b [s]",
            "BGD_L1AE6A [s]",
        ],
        pl.Datetime: [
            "DT",
        ],
    },
}


SBF_BLOCK_COLUMNS_SBF2ASC = {
    "PVTCartesian2": [
        "0",
        "GPST [s]",
        "X [m]",
        "Y [m]",
        "Z [m]",
        "Vx [m/s]",
        "Vy [m/s]",
        "Vz [m/s]",
        "RxClockBias [s]",
        "RxClockDrift [s/s]",
        "NrSV",
        "PVT Mode",
        "MeanCorrAge [0.01 s]",
        "PVT Error",
        "COG [°]",
    ],
    "PVTGeodetic2": [
        "-1",
        "GPST [s]",
        "Latitude [rad]",
        "Longitude [rad]",
        "Height [m]",
        "Undulation [m]",
        "Vn [m/s]",
        "Ve [m/s]",
        "Vu [m/s]",
        "ClockBias [s]",
        "ClockDrift [s/s]",
        "NrSV",
        "PVT Mode",
        "MeanCorrAge [0.01 s]",
        "PVT Error",
        "COG [°]",
    ],
    "PosCovCartesian1": [
        "-2",
        "GPST [s]",
        "Cov_XX [m²]",
        "Cov_YY [m²]",
        "Cov_ZZ [m²]",
        "Cov_tt [s²]",
    ],
}
